### ISSUE TITLE
Cookbook bosh_inception not found

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community-attic/inception-server#11]
```
[2013-05-23T23:30:50+00:00] FATAL: Chef::Exceptions::CookbookNotFound: Cookbook bosh_inception not found. If you're loading bosh_inception from another cookbook, make sure you configure the dependency in your metadata
```

**Comment by drnic** [comment]
`~ubuntu/chef-solo/cookbooks-2` & 1 are missing

**Comment by drnic** [comment]
Ahh, wasn't using 0.3.0.pre4 which has the Berkshelf goodness

**Comment by aeneasr** [comment]
Same issue here, how to solve? I did:

```
$ gem install inception-server
$ inception deploy
```

as suggested here: https://github.com/cloudfoundry-community/bosh-bootstrap#when-do-i-need-an-inception-server

**Comment by drnic** [comment]
Try using "bundle exec inception deploy"

**Comment by aeneasr** [comment]
Thanks, that seems to work :) Should I maybe update the docs accordingly?

**Comment by drnic** [comment]
That'd be great. I think I was always hopeful I'd find a way to get it working from a rubygem :/

**Comment by aeneasr** [comment]
Oh I'm sorry, bundle exec worked when I was in the checked out inception-server repository. Out of the box it tells me: "Could not locate Gemfile or .bundle/ directory"

**Comment by drnic** [comment]
After cloning, change into that new directory, then "bundle install", then the command above.

**Comment by aeneasr** [comment]
Yes, that worked :) Go a different issue now, will create a new issue for that. Thanks for the help!
