### ISSUE TITLE
need to implement bootstrap method for OpenStack

### ISSUE THREAD

**Issue by mstine** [cloudfoundry-community-attic/inception-server#43]
`inception deploy` gets hung here:

https://github.com/cloudfoundry-community/inception-server/blob/master/lib/inception/providers/clients/fog_provider_client.rb#L177-L182

**Comment by drnic** [comment]
Related to #12

**Comment by drnic** [comment]
Fixed by 9fe939e3627bddd23b1407aa09d40fc314257e78
