### ISSUE TITLE
Needs newer ubuntu image

### ISSUE THREAD

**Issue by Errorific** [cloudfoundry-community-attic/inception-server#62]
Hi,

Trying to run this against aws-southeast-2 and its using the 13.04 ubuntu image. This image is EOL and subsequently the raring dist has been removed from the security mirrors resulting in all apt commands failing and provisioning failing.

Thanks.

**Comment by drnic** [comment]
Suggestions for a replacement image?

On Mon, Aug 18, 2014 at 4:28 PM, Errorific notifications@github.com wrote:

> Hi,
> 
> Trying to run this against aws-southeast-2 and its using the 13.04 ubuntu
> image. This image is EOL and subsequently the raring dist has been removed
> from the security mirrors resulting in all apt commands failing and
> provisioning failing.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloudfoundry-community/inception-server/issues/62.

## 

Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic

**Comment by Errorific** [comment]
The standard ubuntu 14.04 one maybe? that should keep working for the next 5 years or so.

I can't figure out how the image selection is being done in the code to try it to see if it will work.

**Comment by drnic** [comment]
Ahh, image select was delegated to cyoi gem -
https://github.com/cloudfoundry-community/cyoi/blob/master/lib/cyoi/providers/clients/aws_provider_client.rb#L136-L158

**Comment by drnic** [comment]
HEAD now supports cyoi 0.11.1 with trusty AMIs
